---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
  namespace: ${NAMESPACE}
  labels:
    app: grafana-server-api
spec:
  selector:
    matchLabels:
      app: grafana-server-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: grafana-server-api
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - name: grafana-server
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: ${PORT_INT}
          protocol: TCP
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bzn-smo-infra-grafana         
                key: GF_SECURITY_ADMIN_PASSWORD 
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-server-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: grafana-server-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${PORT_INT}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: grafana-server-ingress
  annotations:
    allow.http: "true"
spec:
  rules:
    - host: $DNS
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana-server-service
              servicePort: 80