name: Pipeline Deploy JAEGER [SMO]
on:
  pull_request:
    paths:
      - 'app/jaeger/deployment.yml'
      - '.github/workflows/jaeger.yml'   
    branches:
      - 'main'
      - 'develop'
      - 'hotfix/**'
      - 'release/**'
  push:
    paths:
      - 'app/jaeger/deployment.yml'
      - '.github/workflows/jaeger.yml'  
    branches:
      - 'main'    
  workflow_dispatch:
jobs:
  deploy-app:
    name: Pipeline Deploy
    permissions: write-all
    uses: brazona/bzn-pgc-infra/.github/workflows/pipeline-deploy.yml@main
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    with:
      environment_name: INFRASTRUCTURE
      path_app: app/jaeger
      docker_image_tag: latest
      environment_variable_name: JAEGER_INFRASTRUCTURE_ENV   
